/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherNewRouteImport } from './routes/teacher.new'
import { Route as TeacherClassroomsRouteImport } from './routes/teacher.classrooms'
import { Route as TeacherClassroomsIdRouteImport } from './routes/teacher.classrooms.$id'
import { Route as TeacherIdEditRouteImport } from './routes/teacher.$id.edit'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNewRoute = TeacherNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassroomsRoute = TeacherClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassroomsIdRoute = TeacherClassroomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeacherClassroomsRoute,
} as any)
const TeacherIdEditRoute = TeacherIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher/classrooms': typeof TeacherClassroomsRouteWithChildren
  '/teacher/new': typeof TeacherNewRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/$id/edit': typeof TeacherIdEditRoute
  '/teacher/classrooms/$id': typeof TeacherClassroomsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teacher/classrooms': typeof TeacherClassroomsRouteWithChildren
  '/teacher/new': typeof TeacherNewRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/$id/edit': typeof TeacherIdEditRoute
  '/teacher/classrooms/$id': typeof TeacherClassroomsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher/classrooms': typeof TeacherClassroomsRouteWithChildren
  '/teacher/new': typeof TeacherNewRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/$id/edit': typeof TeacherIdEditRoute
  '/teacher/classrooms/$id': typeof TeacherClassroomsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/sitemap.xml'
    | '/teacher'
    | '/teacher/classrooms'
    | '/teacher/new'
    | '/teacher/'
    | '/teacher/$id/edit'
    | '/teacher/classrooms/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/sitemap.xml'
    | '/teacher/classrooms'
    | '/teacher/new'
    | '/teacher'
    | '/teacher/$id/edit'
    | '/teacher/classrooms/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/sitemap.xml'
    | '/teacher'
    | '/teacher/classrooms'
    | '/teacher/new'
    | '/teacher/'
    | '/teacher/$id/edit'
    | '/teacher/classrooms/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/new': {
      id: '/teacher/new'
      path: '/new'
      fullPath: '/teacher/new'
      preLoaderRoute: typeof TeacherNewRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classrooms': {
      id: '/teacher/classrooms'
      path: '/classrooms'
      fullPath: '/teacher/classrooms'
      preLoaderRoute: typeof TeacherClassroomsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classrooms/$id': {
      id: '/teacher/classrooms/$id'
      path: '/$id'
      fullPath: '/teacher/classrooms/$id'
      preLoaderRoute: typeof TeacherClassroomsIdRouteImport
      parentRoute: typeof TeacherClassroomsRoute
    }
    '/teacher/$id/edit': {
      id: '/teacher/$id/edit'
      path: '/$id/edit'
      fullPath: '/teacher/$id/edit'
      preLoaderRoute: typeof TeacherIdEditRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface TeacherClassroomsRouteChildren {
  TeacherClassroomsIdRoute: typeof TeacherClassroomsIdRoute
}

const TeacherClassroomsRouteChildren: TeacherClassroomsRouteChildren = {
  TeacherClassroomsIdRoute: TeacherClassroomsIdRoute,
}

const TeacherClassroomsRouteWithChildren =
  TeacherClassroomsRoute._addFileChildren(TeacherClassroomsRouteChildren)

interface TeacherRouteChildren {
  TeacherClassroomsRoute: typeof TeacherClassroomsRouteWithChildren
  TeacherNewRoute: typeof TeacherNewRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherIdEditRoute: typeof TeacherIdEditRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherClassroomsRoute: TeacherClassroomsRouteWithChildren,
  TeacherNewRoute: TeacherNewRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherIdEditRoute: TeacherIdEditRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
